//! Persisted remote logistics state for the Worm Shrine's outposts.

use crate::state::creatures::Good;
use macroquad_toolkit::grid::TilePos;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// The order in which an outbound worm route fills its limited cargo hold.
/// The default preserves the original route behavior: ore, then ingots, then
/// food above the reserve.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum CargoPriority {
    #[default]
    Ore,
    Ingots,
    Food,
}

impl CargoPriority {
    pub fn next(self) -> Self {
        match self {
            Self::Ore => Self::Ingots,
            Self::Ingots => Self::Food,
            Self::Food => Self::Ore,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::Ore => "Ore first",
            Self::Ingots => "Ingots first",
            Self::Food => "Food first",
        }
    }
}

/// Which automatic route job gets the shared Worm first when more than one
/// policy is ready. The default preserves the original return-first behavior.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum AutoRoutePriority {
    #[default]
    Return,
    Resupply,
    Load,
}

impl AutoRoutePriority {
    pub fn next(self) -> Self {
        match self {
            Self::Return => Self::Resupply,
            Self::Resupply => Self::Load,
            Self::Load => Self::Return,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::Return => "Return first",
            Self::Resupply => "Food first",
            Self::Load => "Load first",
        }
    }

    pub fn job_label(self) -> &'static str {
        match self {
            Self::Return => "cargo return",
            Self::Resupply => "food resupply",
            Self::Load => "outbound load",
        }
    }

    pub fn order(self) -> [Self; 3] {
        match self {
            Self::Return => [Self::Return, Self::Resupply, Self::Load],
            Self::Resupply => [Self::Resupply, Self::Load, Self::Return],
            Self::Load => [Self::Load, Self::Return, Self::Resupply],
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Outpost {
    pub pos: TilePos,
    #[serde(default)]
    pub active: bool,
    #[serde(default)]
    pub cargo_priority: CargoPriority,
    #[serde(default)]
    pub cargo: HashMap<Good, u32>,
    #[serde(default)]
    pub crew: Vec<u32>,
    /// Whether remote scouting is paused while the route remains active.
    #[serde(default)]
    pub expedition_paused: bool,
    /// Seconds accumulated toward the next remote scouting haul.
    #[serde(default)]
    pub expedition_progress: f32,
    /// Number of completed scouting hauls at this remote route.
    #[serde(default)]
    pub expeditions_completed: u32,
    /// Lifetime ore returned by this route's scouting expeditions.
    #[serde(default)]
    pub ore_scouted: u32,
    /// Maximum number of new scouts sent on the next outbound run. `None`
    /// preserves the legacy automatic behavior and fills the remaining crew
    /// capacity.
    #[serde(default)]
    pub crew_dispatch_limit: Option<u32>,
    /// Whether this route has purchased its expanded remote cargo hold.
    #[serde(default)]
    pub storage_upgraded: bool,
    /// Whether this route has purchased its expanded remote camp.
    #[serde(default)]
    pub crew_upgraded: bool,
    /// Whether this route has installed a rig that improves remote surveys.
    #[serde(default)]
    pub survey_upgraded: bool,
    /// Whether this route has installed a beacon that shortens survey cycles.
    #[serde(default)]
    pub resonator_upgraded: bool,
    /// Whether this route has calibrated deep survey data after the Charter.
    #[serde(default)]
    pub deep_survey_upgraded: bool,
    /// Whether this route has installed a post-Relay Signal Cache.
    #[serde(default)]
    pub signal_cache_upgraded: bool,
    /// Lifetime ingots generated by this route's Signal Cache.
    #[serde(default)]
    pub signal_cache_ingots: u32,
    /// Lifetime ingots generated while the network's Wormsong Chorus held.
    #[serde(default)]
    pub chorus_ingots: u32,
    /// Whether this route has installed a post-Convoy Worm Road Waypoint.
    #[serde(default)]
    pub waypoint_upgraded: bool,
    /// Automatically return a full hold as cargo-only, keeping remote crew
    /// stationed for the next expedition.
    #[serde(default)]
    pub auto_return_cargo: bool,
    /// Automatically send cooked food from the warren when remote scouts need
    /// another expedition provision.
    #[serde(default)]
    pub auto_resupply_food: bool,
    /// Automatically launch a standard outbound run whenever this route has
    /// room and cargo or eligible local scouts are ready.
    #[serde(default)]
    pub auto_load: bool,
    #[serde(default)]
    pub last_failure: Option<String>,
}

impl Outpost {
    pub fn new(pos: TilePos) -> Self {
        Self {
            pos,
            active: false,
            cargo_priority: CargoPriority::default(),
            cargo: HashMap::new(),
            crew: Vec::new(),
            expedition_paused: false,
            expedition_progress: 0.0,
            expeditions_completed: 0,
            ore_scouted: 0,
            crew_dispatch_limit: None,
            storage_upgraded: false,
            crew_upgraded: false,
            survey_upgraded: false,
            resonator_upgraded: false,
            deep_survey_upgraded: false,
            signal_cache_upgraded: false,
            signal_cache_ingots: 0,
            chorus_ingots: 0,
            waypoint_upgraded: false,
            auto_return_cargo: false,
            auto_resupply_food: false,
            auto_load: false,
            last_failure: None,
        }
    }

    pub fn cargo_total(&self) -> u32 {
        self.cargo.values().sum()
    }

    pub fn cycle_cargo_priority(&mut self) {
        self.cargo_priority = self.cargo_priority.next();
    }

    pub fn toggle_expedition(&mut self) {
        self.expedition_paused = !self.expedition_paused;
    }

    /// Cycle the number of new scouts on the next outbound run. Automatic
    /// loading is followed by cargo-only, explicit crew counts, then Auto.
    pub fn cycle_crew_dispatch(&mut self, capacity: u32) {
        self.crew_dispatch_limit = match self.crew_dispatch_limit {
            None => Some(0),
            Some(limit) if limit >= capacity => None,
            Some(limit) => Some(limit + 1),
        };
    }

    pub fn crew_dispatch_label(&self, capacity: u32) -> String {
        match self.crew_dispatch_limit {
            None => "Crew per run · Auto".to_owned(),
            Some(0) => "Crew per run · Cargo only".to_owned(),
            Some(limit) => format!("Crew per run · {}/{}", limit.min(capacity), capacity),
        }
    }

    pub fn crew_dispatch_count(&self, remaining_capacity: u32) -> u32 {
        self.crew_dispatch_limit
            .unwrap_or(remaining_capacity)
            .min(remaining_capacity)
    }

    pub fn upgrade_storage(&mut self) {
        self.storage_upgraded = true;
    }

    pub fn crew_capacity(&self, base_capacity: u32, upgraded_capacity: u32) -> u32 {
        if self.crew_upgraded {
            upgraded_capacity.max(base_capacity)
        } else {
            base_capacity
        }
    }

    pub fn upgrade_crew_capacity(&mut self) {
        self.crew_upgraded = true;
    }

    pub fn survey_ore_per_crew(&self, base_yield: u32, upgraded_yield: u32) -> u32 {
        if self.survey_upgraded {
            upgraded_yield.max(base_yield)
        } else {
            base_yield
        }
    }

    pub fn upgrade_survey(&mut self) {
        self.survey_upgraded = true;
    }

    pub fn expedition_cycle_sec(&self, base_cycle: f32, upgraded_cycle: f32) -> f32 {
        if self.resonator_upgraded {
            upgraded_cycle.min(base_cycle)
        } else {
            base_cycle
        }
    }

    pub fn upgrade_resonator(&mut self) {
        self.resonator_upgraded = true;
    }

    pub fn deep_survey_ore_per_crew(
        &self,
        base_yield: u32,
        upgraded_yield: u32,
        deep_yield: u32,
    ) -> u32 {
        if self.deep_survey_upgraded {
            deep_yield.max(upgraded_yield).max(base_yield)
        } else {
            self.survey_ore_per_crew(base_yield, upgraded_yield)
        }
    }

    pub fn upgrade_deep_survey(&mut self) {
        self.deep_survey_upgraded = true;
    }

    pub fn upgrade_signal_cache(&mut self) {
        self.signal_cache_upgraded = true;
    }

    pub fn toggle_auto_return(&mut self) {
        self.auto_return_cargo = !self.auto_return_cargo;
    }

    pub fn auto_return_label(&self) -> &'static str {
        if self.auto_return_cargo {
            "Auto-return · Cargo only"
        } else {
            "Auto-return · Off"
        }
    }

    pub fn toggle_auto_resupply(&mut self) {
        self.auto_resupply_food = !self.auto_resupply_food;
    }

    pub fn auto_resupply_label(&self) -> &'static str {
        if self.auto_resupply_food {
            "Auto-resupply · Food only"
        } else {
            "Auto-resupply · Off"
        }
    }

    pub fn toggle_auto_load(&mut self) {
        self.auto_load = !self.auto_load;
    }

    pub fn auto_load_label(&self) -> &'static str {
        if self.auto_load {
            "Auto-load · Cargo + crew"
        } else {
            "Auto-load · Off"
        }
    }
}

#[cfg(test)]
mod tests;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TransitDirection {
    ToOutpost,
    ToShrine,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TransitCompletion {
    pub direction: TransitDirection,
    pub cargo_units: u32,
    pub passenger_count: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExpeditionCompletion {
    pub outpost: TilePos,
    pub ore: u32,
    pub ingots: u32,
    pub food_spent: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WormTransit {
    pub outpost: TilePos,
    pub direction: TransitDirection,
    pub remaining: f32,
    pub ore: u32,
    pub ingots: u32,
    pub food: f32,
    #[serde(default)]
    pub passengers: Vec<u32>,
}
